/**
 * Cross-compatibility integration test: Python ↔ TypeScript interoperability.
 *
 * Verifies that the TypeScript SDK produces output that is byte-for-byte
 * compatible with the Python Qubes backend across every layer of the stack:
 *
 *   1. Block hash compatibility      — hashBlock() matches Python hash_block()
 *   2. Signature cross-verification  — DER format, Python sig verifiable in TS
 *   3. Package format compatibility  — Binary header layout & .qube ZIP structure
 *   4. Block structure compatibility — toDict() uses snake_case, correct fields
 *   5. Chain state compatibility     — version "2.0", all 15 sections present
 *   6. Merkle root compatibility     — matches Python vectors for all tree shapes
 *   7. ECIES format compatibility    — ephemeral_pubkey(33) || nonce(12) || ct+tag
 */
import { describe, it, expect } from 'vitest';
import { unzipSync } from 'fflate';

// ── Crypto primitives ────────────────────────────────────────────────────────
import { hashBlock, signBlock, verifyBlockSignature } from '../../src/crypto/signing.js';
import { privateKeyFromHex, getPublicKey, serializePublicKey } from '../../src/crypto/keys.js';
import { deriveCommitment, deriveQubeId } from '../../src/crypto/identity.js';
import { computeMerkleRoot } from '../../src/crypto/merkle.js';
import { eciesEncrypt, eciesDecrypt } from '../../src/crypto/ecies.js';

// ── Block factories ──────────────────────────────────────────────────────────
import { QubeBlock } from '../../src/blocks/block.js';
import { createGenesisBlock } from '../../src/blocks/genesis.js';
import { createMessageBlock } from '../../src/blocks/memory.js';
import { createDefaultChainState } from '../../src/blocks/chain-state.js';

// ── Package format ───────────────────────────────────────────────────────────
import {
  createBinaryPackage,
  createQubeFile,
  PACKAGE_MAGIC,
  PACKAGE_VERSION,
  NONCE_SIZE,
} from '../../src/package/create.js';
import { parseBinaryPackage, parseQubeFile } from '../../src/package/parse.js';
import { verifyPackageIntegrity } from '../../src/package/verify.js';
import type { QubePackageData } from '../../src/types/package.js';

// ── Test vectors (generated by generate-vectors.py) ─────────────────────────
import vectors from '../compat/vectors.json';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fromHex(hex: string): Uint8Array {
  const len = hex.length >>> 1;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

function toHex(bytes: Uint8Array): string {
  let hex = '';
  for (let i = 0; i < bytes.length; i++) {
    hex += bytes[i].toString(16).padStart(2, '0');
  }
  return hex;
}

// Private key from the shared test vector set
const PRIVATE_KEY = privateKeyFromHex(vectors.keyDerivation.privateKeyHex);
const PUBLIC_KEY = getPublicKey(PRIVATE_KEY);

// ---------------------------------------------------------------------------
// 1. Block hash compatibility
// ---------------------------------------------------------------------------
//
// Python: hash_block(block) = SHA-256(json.dumps(block, sort_keys=True))
// TS:     hashBlock(block)  = SHA-256(canonicalStringify(block))
//
// Both implementations must agree on every vector in vectors.json.

describe('1. Block hash compatibility ↔ Python hash_block()', () => {
  it('genesis block hash matches the Python-generated vector', () => {
    const hash = hashBlock(vectors.blockHashing.block);
    expect(hash).toBe(vectors.blockHashing.blockHash);
    // Sanity-check the known value from the generate-vectors.py output
    expect(hash).toBe('5d67be372c67d2925abe720cc3252d152fb02cd7e746d4c7b7884bf0e90135a0');
  });

  it('standard block hash (block_number=1) matches the Python-generated vector', () => {
    const hash = hashBlock(vectors.blockSigningStandard.block);
    expect(hash).toBe(vectors.blockSigningStandard.blockHash);
    expect(hash).toBe('23f449eac9e2376c588ab3cf7a77454fae5c7fdb6b6b2f7e501b01730e587443');
  });

  it('hash is deterministic: same dict always produces the same hash', () => {
    const block = {
      block_number: 5,
      timestamp: '2025-06-01T12:00:00Z',
      qube_id: 'AABBCCDD',
      data: { content: 'determinism test', nested: { x: 1, y: 2 } },
      previous_hash: 'f'.repeat(64),
    };

    const hash1 = hashBlock(block);
    const hash2 = hashBlock(block);
    expect(hash1).toBe(hash2);
    expect(hash1).toMatch(/^[0-9a-f]{64}$/);
  });

  it('block_hash and signature fields are excluded from the hash input', () => {
    const base = {
      block_number: 1,
      timestamp: '2025-01-01T00:01:00Z',
      qube_id: 'F909521D',
      data: { message: 'hello world' },
      previous_hash: '5d67be372c67d2925abe720cc3252d152fb02cd7e746d4c7b7884bf0e90135a0',
    };

    const withExtra = {
      ...base,
      block_hash: 'some_existing_hash_that_must_not_affect_the_result',
      signature: 'some_existing_signature_that_must_not_affect_the_result',
    };

    expect(hashBlock(base)).toBe(hashBlock(withExtra));
  });
});

// ---------------------------------------------------------------------------
// 2. Signature cross-verification
// ---------------------------------------------------------------------------
//
// DER-encoded ECDSA signatures must be interoperable. Python's cryptography
// library produces DER format; the TS SDK must verify them and vice-versa.

describe('2. Signature cross-verification ↔ Python sign_block()', () => {
  it('Python genesis signature is verifiable by TS verifyBlockSignature()', () => {
    const block = vectors.blockSigningGenesis.block;
    const pythonSig = vectors.blockSigningGenesis.signature;
    const pubKey = fromHex(vectors.blockSigningGenesis.publicKeyHex);

    expect(verifyBlockSignature(block, pythonSig, pubKey)).toBe(true);
  });

  it('Python standard block signature is verifiable by TS verifyBlockSignature()', () => {
    const block = vectors.blockSigningStandard.block;
    const pythonSig = vectors.blockSigningStandard.signature;
    const pubKey = fromHex(vectors.blockSigningStandard.publicKeyHex);

    expect(verifyBlockSignature(block, pythonSig, pubKey)).toBe(true);
  });

  it('TS genesis signature is DER-encoded (starts with 0x30)', () => {
    const block = vectors.blockSigningGenesis.block;
    const sig = signBlock(block, PRIVATE_KEY);

    // DER SEQUENCE tag = 0x30
    const firstByte = parseInt(sig.substring(0, 2), 16);
    expect(firstByte).toBe(0x30);
  });

  it('TS standard signature is DER-encoded (starts with 0x30)', () => {
    const block = vectors.blockSigningStandard.block;
    const sig = signBlock(block, PRIVATE_KEY);

    const firstByte = parseInt(sig.substring(0, 2), 16);
    expect(firstByte).toBe(0x30);
  });

  it('TS genesis signature round-trips (sign → verify with same pubkey)', () => {
    const block = vectors.blockSigningGenesis.block;
    const sig = signBlock(block, PRIVATE_KEY);

    expect(verifyBlockSignature(block, sig, PUBLIC_KEY)).toBe(true);
  });

  it('TS standard signature round-trips (sign → verify with same pubkey)', () => {
    const block = vectors.blockSigningStandard.block;
    const sig = signBlock(block, PRIVATE_KEY);

    expect(verifyBlockSignature(block, sig, PUBLIC_KEY)).toBe(true);
  });

  it('invalid hex signature returns false (not throws)', () => {
    const block = vectors.blockSigningGenesis.block;
    expect(verifyBlockSignature(block, 'deadbeef', PUBLIC_KEY)).toBe(false);
  });

  it('signature from a different key does not verify', () => {
    // Generate a fresh random-ish key (different from PRIVATE_KEY)
    const otherKey = fromHex('a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90');
    const block = vectors.blockSigningGenesis.block;
    const sig = signBlock(block, otherKey);

    // Must not verify against the original public key
    expect(verifyBlockSignature(block, sig, PUBLIC_KEY)).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// 3. Package format compatibility
// ---------------------------------------------------------------------------
//
// Python: create_package() → [4 QUBE magic][1 version][12 nonce][N ciphertext+tag]
// TS:     createBinaryPackage() must produce the identical layout.
//
// .qube ZIP format: manifest.json (plain) + data.enc (AES-256-GCM, no nonce prepended).

function makePackageData(): QubePackageData {
  return {
    metadata: {
      qubeId: 'F909521D',
      qubeName: 'Cross Compat Qube',
      publicKey: vectors.keyDerivation.publicKeyHex,
      chainLength: 1,
      merkleRoot: vectors.blockHashing.blockHash,
      packageVersion: '1.0',
      packagedAt: 1735689600, // 2025-01-01T00:00:00Z
      packagedBy: 'test-suite',
      hasNft: false,
    },
    genesisBlock: {
      block_number: 0,
      block_type: 'GENESIS',
      block_hash: vectors.blockHashing.blockHash,
      qube_id: 'F909521D',
      timestamp: 1735689600,
    },
    memoryBlocks: [],
    chainState: { version: '2.0', qube_id: 'F909521D' },
  };
}

describe('3a. Binary package format ↔ Python create_package()', () => {
  it('magic bytes are ASCII "QUBE" (0x51 0x55 0x42 0x45)', async () => {
    const { encrypted } = await createBinaryPackage(makePackageData());

    expect(encrypted[0]).toBe(0x51); // Q
    expect(encrypted[1]).toBe(0x55); // U
    expect(encrypted[2]).toBe(0x42); // B
    expect(encrypted[3]).toBe(0x45); // E
  });

  it('version byte at offset 4 is 0x01', async () => {
    const { encrypted } = await createBinaryPackage(makePackageData());
    expect(encrypted[4]).toBe(PACKAGE_VERSION);
    expect(encrypted[4]).toBe(0x01);
  });

  it('nonce occupies bytes 5–16 (12 bytes, matching NONCE_SIZE)', async () => {
    const { encrypted } = await createBinaryPackage(makePackageData());
    const nonce = encrypted.slice(5, 5 + NONCE_SIZE);
    expect(nonce.length).toBe(12);
  });

  it('total layout is [4 magic][1 version][12 nonce][plaintext_len + 16 tag]', async () => {
    const data = makePackageData();
    const plaintext = new TextEncoder().encode(JSON.stringify(data));
    const { encrypted } = await createBinaryPackage(data);

    const expectedLen = 4 + 1 + 12 + plaintext.length + 16;
    expect(encrypted.length).toBe(expectedLen);
  });

  it('createBinaryPackage → parseBinaryPackage round-trip restores data exactly', async () => {
    const original = makePackageData();
    const key = new Uint8Array(32).fill(0xab);
    const { encrypted } = await createBinaryPackage(original, key);
    const parsed = await parseBinaryPackage(encrypted, key);

    expect(parsed.metadata.qubeId).toBe(original.metadata.qubeId);
    expect(parsed.metadata.qubeName).toBe(original.metadata.qubeName);
    expect(parsed.metadata.merkleRoot).toBe(original.metadata.merkleRoot);
    expect(parsed.genesisBlock).toEqual(original.genesisBlock);
    expect(parsed.memoryBlocks).toEqual(original.memoryBlocks);
    expect(parsed.chainState).toEqual(original.chainState);
  });
});

describe('3b. .qube ZIP format ↔ Python export_qube_to_file()', () => {
  it('ZIP contains exactly manifest.json and data.enc', async () => {
    const zipBytes = await createQubeFile(makePackageData(), 'password');
    const files = unzipSync(zipBytes);

    expect(files['manifest.json']).toBeDefined();
    expect(files['data.enc']).toBeDefined();
    // No extra files
    expect(Object.keys(files)).toHaveLength(2);
  });

  it('manifest.json has qubeId, salt (32 hex chars), and nonce (24 hex chars)', async () => {
    const data = makePackageData();
    const zipBytes = await createQubeFile(data, 'test-password');
    const files = unzipSync(zipBytes);
    const manifest = JSON.parse(new TextDecoder().decode(files['manifest.json']));

    expect(manifest.qubeId).toBe(data.metadata.qubeId);
    // Salt = 16 bytes = 32 hex chars
    expect(manifest.salt).toMatch(/^[0-9a-f]{32}$/);
    // Nonce = 12 bytes = 24 hex chars
    expect(manifest.nonce).toMatch(/^[0-9a-f]{24}$/);
    // Version matches Python's "1.0"
    expect(manifest.version).toBe('1.0');
  });

  it('data.enc length is plaintext_len + 16 (no nonce prepended, nonce is in manifest)', async () => {
    const data = makePackageData();
    const plaintext = new TextEncoder().encode(JSON.stringify(data));
    const zipBytes = await createQubeFile(data, 'pw');
    const files = unzipSync(zipBytes);

    // Python stores the nonce in manifest.json and data.enc is ciphertext-only
    expect(files['data.enc'].length).toBe(plaintext.length + 16);
  });

  it('createQubeFile → parseQubeFile round-trip restores data exactly', async () => {
    const original = makePackageData();
    const password = 'cross-compat-test-password';
    const zipBytes = await createQubeFile(original, password);
    const parsed = await parseQubeFile(zipBytes, password);

    expect(parsed.metadata.qubeId).toBe(original.metadata.qubeId);
    expect(parsed.genesisBlock).toEqual(original.genesisBlock);
    expect(parsed.chainState).toEqual(original.chainState);
  });

  it('wrong password fails decryption (simulates Python receiving a TS-created file)', async () => {
    const zipBytes = await createQubeFile(makePackageData(), 'correct-password');
    await expect(parseQubeFile(zipBytes, 'wrong-password')).rejects.toThrow(/decrypt/i);
  });
});

// ---------------------------------------------------------------------------
// 4. Block structure compatibility
// ---------------------------------------------------------------------------
//
// Python's Block.to_dict() uses model_dump(exclude_none=True) with snake_case.
// TS QubeBlock.toDict() must produce the same key names and structure.

describe('4. Block structure compatibility ↔ Python Block.to_dict()', () => {
  it('genesis block toDict() uses snake_case keys', () => {
    const genesis = createGenesisBlock({
      qubeId: 'F909521D',
      qubeName: 'Test Qube',
      creator: 'user_abc',
      publicKey: vectors.keyDerivation.publicKeyHex,
      genesisPrompt: 'You are a test assistant.',
      aiModel: 'claude-sonnet-4-20250514',
      voiceModel: 'openai:alloy',
      avatar: { type: 'default' },
    });

    const dict = genesis.toDict();

    // Core snake_case fields that Python produces
    expect(dict).toHaveProperty('block_type', 'GENESIS');
    expect(dict).toHaveProperty('block_number', 0);
    expect(dict).toHaveProperty('qube_id', 'F909521D');
    expect(dict).toHaveProperty('qube_name', 'Test Qube');
    expect(dict).toHaveProperty('creator', 'user_abc');
    expect(dict).toHaveProperty('public_key', vectors.keyDerivation.publicKeyHex);
    expect(dict).toHaveProperty('genesis_prompt', 'You are a test assistant.');
    expect(dict).toHaveProperty('ai_model', 'claude-sonnet-4-20250514');
    expect(dict).toHaveProperty('voice_model', 'openai:alloy');
    expect(dict).toHaveProperty('previous_hash', '0'.repeat(64));
    expect(dict).toHaveProperty('block_hash');
    expect(dict).toHaveProperty('encrypted', false);
    expect(dict).toHaveProperty('temporary', false);

    // Verify NO camelCase keys leaked through
    expect(dict).not.toHaveProperty('blockType');
    expect(dict).not.toHaveProperty('blockNumber');
    expect(dict).not.toHaveProperty('qubeId');
    expect(dict).not.toHaveProperty('qubeName');
    expect(dict).not.toHaveProperty('publicKey');
    expect(dict).not.toHaveProperty('previousHash');
    expect(dict).not.toHaveProperty('blockHash');
  });

  it('genesis block_hash is a 64-char lowercase hex string', () => {
    const genesis = createGenesisBlock({
      qubeId: 'F909521D',
      qubeName: 'Test Qube',
      creator: 'user_abc',
      publicKey: vectors.keyDerivation.publicKeyHex,
      genesisPrompt: 'You are a test assistant.',
      aiModel: 'claude-sonnet-4-20250514',
      voiceModel: 'openai:alloy',
      avatar: {},
    });

    const dict = genesis.toDict();
    expect(typeof dict.block_hash).toBe('string');
    expect(dict.block_hash as string).toMatch(/^[0-9a-f]{64}$/);
  });

  it('genesis previous_hash is 64 zeros (Python sentinel value)', () => {
    const genesis = createGenesisBlock({
      qubeId: 'TEST0001',
      qubeName: 'Chain Start',
      creator: 'user1',
      publicKey: vectors.keyDerivation.publicKeyHex,
      genesisPrompt: 'Hello.',
      aiModel: 'claude-opus-4-20250514',
      voiceModel: 'openai:alloy',
      avatar: {},
    });

    const dict = genesis.toDict();
    expect(dict.previous_hash).toBe('0'.repeat(64));
  });

  it('memory block toDict() has all required snake_case fields', () => {
    const genesisHash = vectors.blockHashing.blockHash;
    const block = createMessageBlock({
      qubeId: 'F909521D',
      blockNumber: 1,
      previousHash: genesisHash,
      messageType: 'qube_to_human',
      recipientId: 'owner_user',
      messageBody: 'Hello from the cross-compat test',
      conversationId: 'conv-001',
    });

    const dict = block.toDict();

    expect(dict).toHaveProperty('block_type', 'MESSAGE');
    expect(dict).toHaveProperty('block_number', 1);
    expect(dict).toHaveProperty('qube_id', 'F909521D');
    expect(dict).toHaveProperty('previous_hash', genesisHash);
    expect(dict).toHaveProperty('block_hash');
    expect(dict).toHaveProperty('encrypted', true);
    expect(dict).toHaveProperty('temporary', false);
    expect(dict).toHaveProperty('content');

    const content = dict.content as Record<string, unknown>;
    expect(content).toHaveProperty('message_type', 'qube_to_human');
    expect(content).toHaveProperty('message_body', 'Hello from the cross-compat test');
    expect(content).toHaveProperty('conversation_id', 'conv-001');

    // No camelCase pollution in block-level keys
    expect(dict).not.toHaveProperty('blockType');
    expect(dict).not.toHaveProperty('blockNumber');
    expect(dict).not.toHaveProperty('qubeId');
    expect(dict).not.toHaveProperty('previousHash');
    expect(dict).not.toHaveProperty('blockHash');
  });

  it('toDict() excludes null values (matches Python exclude_none=True)', () => {
    // Create a block with explicitly null fields
    const block = new QubeBlock({
      block_type: 'MESSAGE',
      block_number: 1,
      qube_id: 'F909521D',
      timestamp: 1735689600,
      previous_hash: 'a'.repeat(64),
      block_hash: null,
      signature: null,
      merkle_root: null,
      content: {},
      encrypted: false,
      temporary: false,
    });

    const dict = block.toDict();

    // Null fields must be absent (Python model_dump(exclude_none=True))
    expect(dict).not.toHaveProperty('block_hash');
    expect(dict).not.toHaveProperty('signature');
    expect(dict).not.toHaveProperty('merkle_root');

    // Non-null fields must be present
    expect(dict).toHaveProperty('block_type', 'MESSAGE');
    expect(dict).toHaveProperty('previous_hash', 'a'.repeat(64));
  });

  it('block hash computed over the dict matches hashBlock() on the same dict', () => {
    // This is the core invariant: computeHash() must equal what Python's hash_block()
    // would produce on the toDict() output.
    const genesis = createGenesisBlock({
      qubeId: 'F909521D',
      qubeName: 'Invariant Qube',
      creator: 'user_x',
      publicKey: vectors.keyDerivation.publicKeyHex,
      genesisPrompt: 'invariant test',
      aiModel: 'claude-sonnet-4-20250514',
      voiceModel: 'openai:alloy',
      avatar: {},
    });

    const dict = genesis.toDict();

    // The stored block_hash must match what hashBlock() computes on the same dict
    // (after stripping block_hash itself, as hashBlock does internally)
    const recomputed = genesis.computeHash();
    expect(dict.block_hash).toBe(recomputed);
  });
});

// ---------------------------------------------------------------------------
// 5. Chain state compatibility
// ---------------------------------------------------------------------------
//
// Python: create_default_chain_state() returns a dict with version "2.0"
// and exactly 15 top-level sections (version + qube_id + last_updated + 12 named sections).
// TS: createDefaultChainState() must match.

describe('5. Chain state compatibility ↔ Python create_default_chain_state()', () => {
  const GENESIS_BLOCK: Record<string, unknown> = {
    block_type: 'GENESIS',
    block_number: 0,
    qube_id: 'F909521D',
    timestamp: 1735689600,
    birth_timestamp: 1735689600,
    qube_name: 'Compat Qube',
    creator: 'user_abc',
    public_key: vectors.keyDerivation.publicKeyHex,
    genesis_prompt: 'You are a compatibility test.',
    ai_model: 'claude-sonnet-4-20250514',
    voice_model: 'openai:alloy',
    avatar: {},
    block_hash: vectors.blockHashing.blockHash,
  };

  it('version is "2.0"', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    expect(state.version).toBe('2.0');
  });

  it('has exactly 15 top-level sections', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    const keys = Object.keys(state);

    // All 15 expected sections
    const EXPECTED_SECTIONS = [
      'version',
      'qube_id',
      'last_updated',
      'chain',
      'session',
      'settings',
      'runtime',
      'stats',
      'block_counts',
      'skills',
      'relationships',
      'financial',
      'mood',
      'owner_info',
      'qube_profile',
      'health',
      'attestation',
    ];

    // Verify each expected section is present
    for (const section of EXPECTED_SECTIONS) {
      expect(keys, `missing section: ${section}`).toContain(section);
    }

    // Count: version + qube_id + last_updated + 12 named sections = 15 minimum
    expect(keys.length).toBeGreaterThanOrEqual(15);
  });

  it('qube_id is passed through correctly', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    expect(state.qube_id).toBe('F909521D');
  });

  it('chain section has correct initial values', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    const chain = state.chain as Record<string, unknown>;

    expect(chain.length).toBe(1);
    expect(chain.latest_block_number).toBe(0);
    expect(chain.total_blocks).toBe(1);
    expect(chain.permanent_blocks).toBe(1);
    expect(chain.session_blocks).toBe(0);
    expect(chain.genesis_hash).toBe(vectors.blockHashing.blockHash);
    expect(chain.latest_block_hash).toBe(vectors.blockHashing.blockHash);
  });

  it('block_counts section initializes GENESIS=1, all others=0', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    const counts = state.block_counts as Record<string, number>;

    expect(counts.GENESIS).toBe(1);
    expect(counts.MESSAGE).toBe(0);
    expect(counts.ACTION).toBe(0);
    expect(counts.SUMMARY).toBe(0);
    expect(counts.GAME).toBe(0);
  });

  it('stats section has all usage counters zeroed', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    const stats = state.stats as Record<string, unknown>;

    expect(stats.total_messages_sent).toBe(0);
    expect(stats.total_messages_received).toBe(0);
    expect(stats.total_tokens_used).toBe(0);
    expect(stats.total_api_cost).toBe(0.0);
    expect(stats.total_tool_calls).toBe(0);
    expect(stats.total_anchors).toBe(0);
  });

  it('settings.model_locked is true and model_locked_to matches genesis ai_model', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    const settings = state.settings as Record<string, unknown>;

    expect(settings.model_locked).toBe(true);
    expect(settings.model_locked_to).toBe('claude-sonnet-4-20250514');
    expect(settings.voice_model).toBe('openai:alloy');
  });

  it('ai provider is detected as "anthropic" for a claude model', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    const runtime = state.runtime as Record<string, unknown>;
    expect(runtime.current_provider).toBe('anthropic');
  });

  it('mood section defaults to neutral state', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    const mood = state.mood as Record<string, unknown>;

    expect(mood.current).toBe('neutral');
    expect(mood.intensity).toBe(0.5);
  });

  it('health.overall_status is "healthy"', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    const health = state.health as Record<string, unknown>;
    expect(health.overall_status).toBe('healthy');
  });

  it('attestation.verified is false on creation', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');
    const attestation = state.attestation as Record<string, unknown>;
    expect(attestation.verified).toBe(false);
  });

  it('all section keys are snake_case (no camelCase)', () => {
    const state = createDefaultChainState(GENESIS_BLOCK, 'F909521D');

    // Every top-level key must be snake_case
    for (const key of Object.keys(state)) {
      expect(key, `top-level key "${key}" is camelCase`).toMatch(/^[a-z][a-z0-9_]*$/);
    }

    // Spot-check nested sections
    const chain = state.chain as Record<string, unknown>;
    for (const key of Object.keys(chain)) {
      expect(key, `chain key "${key}" is camelCase`).toMatch(/^[a-z][a-z0-9_]*$/);
    }
  });
});

// ---------------------------------------------------------------------------
// 6. Merkle root compatibility
// ---------------------------------------------------------------------------
//
// Python: compute_merkle_root(hashes) using string concatenation + SHA-256.
// TS:     computeMerkleRoot(hashes) must produce identical results.

describe('6. Merkle root compatibility ↔ Python compute_merkle_root()', () => {
  for (const tc of vectors.merkleRoot.cases) {
    it(`${tc.name}: root matches Python vector`, () => {
      const root = computeMerkleRoot(tc.hashes);
      expect(root).toBe(tc.root);
    });
  }

  it('empty list returns 64 zero characters', () => {
    expect(computeMerkleRoot([])).toBe('0'.repeat(64));
  });

  it('single hash returns itself unchanged', () => {
    const hash = 'a'.repeat(64);
    expect(computeMerkleRoot([hash])).toBe(hash);
  });

  it('can verify a chain of block hashes from the compat vectors', () => {
    // Simulate a 2-block chain: genesis + one memory block
    const genesisHash = vectors.blockHashing.blockHash;
    const standardHash = vectors.blockSigningStandard.blockHash;
    const root = computeMerkleRoot([genesisHash, standardHash]);

    // Verify the root is deterministic
    expect(root).toBe(computeMerkleRoot([genesisHash, standardHash]));
    expect(root).toMatch(/^[0-9a-f]{64}$/);
  });

  it('verifyPackageIntegrity uses Merkle root to confirm chain tamper-detection', () => {
    // Construct a minimal package where we know the Merkle root
    const genesisHash = 'a'.repeat(64);
    const block1Hash = 'b'.repeat(64);
    const correctRoot = computeMerkleRoot([genesisHash, block1Hash]);

    const validPackage: QubePackageData = {
      metadata: {
        qubeId: 'TEST0001',
        qubeName: 'Test',
        publicKey: vectors.keyDerivation.publicKeyHex,
        chainLength: 2,
        merkleRoot: correctRoot,
        packageVersion: '1.0',
        packagedAt: 1735689600,
        packagedBy: 'test',
        hasNft: false,
      },
      genesisBlock: { block_hash: genesisHash },
      memoryBlocks: [{ block_hash: block1Hash }],
      chainState: {},
    };

    expect(verifyPackageIntegrity(validPackage)).toBe(true);

    // Tamper with a block hash — integrity check must fail
    const tamperedPackage = {
      ...validPackage,
      memoryBlocks: [{ block_hash: 'c'.repeat(64) }],
    };
    expect(verifyPackageIntegrity(tamperedPackage)).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// 7. ECIES format compatibility
// ---------------------------------------------------------------------------
//
// Python: ephemeral_pubkey(33) || nonce(12) || ciphertext+tag
// TS:     eciesEncrypt() must produce the same layout.

describe('7. ECIES format compatibility ↔ Python ecies_encrypt()', () => {
  const RECIPIENT_PRIVATE_KEY = fromHex(vectors.ecies.recipientPrivateKeyHex);
  const RECIPIENT_PUBLIC_KEY = fromHex(vectors.ecies.recipientPublicKeyHex);

  it('Python-generated ECIES ciphertext is decryptable by TS eciesDecrypt()', async () => {
    const ciphertextBytes = fromHex(vectors.ecies.ciphertextHex);
    const decrypted = await eciesDecrypt(ciphertextBytes, RECIPIENT_PRIVATE_KEY);

    expect(new TextDecoder().decode(decrypted)).toBe(vectors.ecies.plaintext);
  });

  it('ciphertext layout is ephemeral_pubkey(33) || nonce(12) || ciphertext+tag', async () => {
    const plaintext = new TextEncoder().encode('test payload for format check');
    const ciphertext = await eciesEncrypt(plaintext, RECIPIENT_PUBLIC_KEY);

    // Minimum length: 33 + 12 + 16 (tag, no payload stripped) + payload
    expect(ciphertext.length).toBeGreaterThanOrEqual(33 + 12 + 16);

    // ephemeral pubkey at offset 0 must be compressed: prefix byte 02 or 03
    const prefixByte = ciphertext[0];
    expect(prefixByte === 0x02 || prefixByte === 0x03).toBe(true);
  });

  it('ephemeral pubkey prefix is 0x02 or 0x03 (compressed secp256k1)', async () => {
    const ciphertextBytes = fromHex(vectors.ecies.ciphertextHex);

    // First byte of the Python-generated ciphertext
    expect(ciphertextBytes[0] === 0x02 || ciphertextBytes[0] === 0x03).toBe(true);

    // First byte of the Python ephemeral public key from the vector
    const ephemeralPubKey = fromHex(vectors.ecies.ephemeralPublicKeyHex);
    expect(ephemeralPubKey[0] === 0x02 || ephemeralPubKey[0] === 0x03).toBe(true);

    // First 33 bytes of ciphertext must equal the ephemeral public key
    const embeddedPubKey = ciphertextBytes.slice(0, 33);
    expect(toHex(embeddedPubKey)).toBe(vectors.ecies.ephemeralPublicKeyHex);
  });

  it('nonce occupies bytes 33–44 (12 bytes) in Python ciphertext', () => {
    const ciphertextBytes = fromHex(vectors.ecies.ciphertextHex);
    const nonce = ciphertextBytes.slice(33, 33 + 12);
    expect(toHex(nonce)).toBe(vectors.ecies.nonceHex);
  });

  it('TS eciesEncrypt → eciesDecrypt round-trip with recipient keys', async () => {
    const plaintext = new TextEncoder().encode('round-trip test payload');
    const ciphertext = await eciesEncrypt(plaintext, RECIPIENT_PUBLIC_KEY);
    const recovered = await eciesDecrypt(ciphertext, RECIPIENT_PRIVATE_KEY);

    expect(new TextDecoder().decode(recovered)).toBe('round-trip test payload');
  });

  it('wrong private key fails decryption', async () => {
    const plaintext = new TextEncoder().encode('private key mismatch test');
    const ciphertext = await eciesEncrypt(plaintext, RECIPIENT_PUBLIC_KEY);

    // Use a different private key (the signing key from the compat tests)
    const wrongKey = PRIVATE_KEY;
    await expect(eciesDecrypt(ciphertext, wrongKey)).rejects.toThrow();
  });

  it('ciphertext total length is 33 + 12 + plaintext_length + 16', async () => {
    const msg = 'length check test payload';
    const plaintext = new TextEncoder().encode(msg);
    const ciphertext = await eciesEncrypt(plaintext, RECIPIENT_PUBLIC_KEY);

    const expectedLen = 33 + 12 + plaintext.length + 16;
    expect(ciphertext.length).toBe(expectedLen);
  });
});

// ---------------------------------------------------------------------------
// 8. Identity derivation compatibility (bonus — ties back to signing vectors)
// ---------------------------------------------------------------------------
//
// Python: derive_commitment = SHA-256(pubkey_hex_STRING)
//         derive_qube_id    = commitment[:8].upper()

describe('8. Identity derivation compatibility ↔ Python derive_commitment / derive_qube_id', () => {
  it('commitment matches Python vector', () => {
    const pubKeyHex = vectors.keyDerivation.publicKeyHex;
    const commitment = deriveCommitment(pubKeyHex);
    expect(commitment).toBe(vectors.commitment.commitment);
    // Known value from generate-vectors.py
    expect(commitment).toBe('f909521ddd38df95d0bb67c5f99960f558a1eeb19936702a383a23d792162ab6');
  });

  it('qubeId matches Python vector (first 8 chars of commitment, uppercased)', () => {
    const pubKeyHex = vectors.keyDerivation.publicKeyHex;
    const qubeId = deriveQubeId(pubKeyHex);
    expect(qubeId).toBe(vectors.qubeId.qubeId);
    expect(qubeId).toBe('F909521D');
  });

  it('public key serialization matches Python compressed key hex', () => {
    const pubKey = getPublicKey(PRIVATE_KEY);
    const hex = serializePublicKey(pubKey);
    expect(hex).toBe(vectors.keyDerivation.publicKeyHex);
    expect(hex).toHaveLength(66);
    // Compressed key prefix
    expect(hex.substring(0, 2) === '02' || hex.substring(0, 2) === '03').toBe(true);
  });
});
