import { Qube } from '../types';

export const MOCK_QUBES: Qube[] = [
  {
    qube_id: 'qube_001',
    name: 'Athena',
    genesis_prompt: 'A knowledgeable AI assistant specializing in research and analysis',
    ai_provider: 'openai',
    ai_model: 'gpt-4',
    favorite_color: '#00ff88',
    created_at: '2025-10-01T12:00:00Z',
    trust_score: 95,
    memory_blocks_count: 15400,
    friends_count: 23,
    status: 'active',
  },
  {
    qube_id: 'qube_002',
    name: 'Hermes',
    genesis_prompt: 'A creative AI assistant focused on writing and communication',
    ai_provider: 'anthropic',
    ai_model: 'claude-4.5',
    favorite_color: '#b47cff',
    created_at: '2025-10-02T14:30:00Z',
    trust_score: 87,
    memory_blocks_count: 8200,
    friends_count: 15,
    status: 'active',
  },
  {
    qube_id: 'qube_003',
    name: 'Prometheus',
    genesis_prompt: 'A technical AI assistant skilled in coding and system design',
    ai_provider: 'google',
    ai_model: 'gemini-2.5',
    favorite_color: '#00d4ff',
    created_at: '2025-10-03T09:15:00Z',
    trust_score: 92,
    memory_blocks_count: 12100,
    friends_count: 18,
    status: 'inactive',
  },
  {
    qube_id: 'qube_004',
    name: 'Apollo',
    genesis_prompt: 'An analytical AI assistant for data science and mathematics',
    ai_provider: 'openai',
    ai_model: 'gpt-5',
    favorite_color: '#ffaa00',
    created_at: '2025-10-04T16:45:00Z',
    trust_score: 89,
    memory_blocks_count: 6800,
    friends_count: 12,
    status: 'busy',
  },
];
